### ISSUE TITLE
FreshwaterOS?

### ISSUE THREAD

**Issue by itslychee** [auxolotl/templates#23]
Hi I'm curious as to where the name comes from in this particular spot of the README? Shouldn't it be called AuxOS instead? I don't remember a particular name being agreed upon as of writing this. 
![image](https://github.com/auxolotl/templates/assets/82718618/b2e54f9c-adee-4fd0-9fe7-43d9a981ef30)

**Comment by isabelroses** [comment]
At the point of creation of this repo the main suggestion was FreshwaterOS. And I don't think we decided on AuxOS either. But we have been using Aux X as placeholder names.

**Comment by aprilthepink** [comment]
lmao freshwaterOS is fine and hilarious, i like it

**Comment by TheCodedProf** [comment]
I've changed the line to say Auxolotl system until we decide on an actual OS name
