### ISSUE TITLE
CI to ensure formatting?

### ISSUE THREAD

**Issue by AxelSilverdew** [auxolotl/templates#24]
To ensure that templates are always formatted properly, should we include a simple CI check to make sure that PRs are always formatted with nixfmt before we merge them?

Forgejo is compatible with the github actions yml, so when we move over the CI will move over too, so this won't be tying us down to GitHub in any way.

**Comment by liketechnik** [comment]
Yes please, see also the discussion at https://forum.aux.computer/t/reviewing-and-merging-pr-mrs/316/15?u=liketechnik:

>> If you like it, put a lint rule on it

> A large amount of the nits can be taken care of via automation (formatter, linter, tests). We should not have to waste effort on these things.

**Comment by AxelSilverdew** [comment]
Alrighty, gonna open a PR with this then.

**Comment by AxelSilverdew** [comment]
Opened a PR here: https://github.com/auxolotl/templates/pull/25
