### ISSUE TITLE
warning: unknown experimental feature 'flake'

### ISSUE THREAD

**Issue by ztr-pen** [auxolotl/templates#29]
Trying to get started on Nixos 24.05 (unstable) on existing linux system. Running command: 
`nix --extra-experimental-features nix-command --extra-experimental-features flake new -t github:auxolotl/templates#system NixFiles`

Returns warning:
`warning: unknown experimental feature 'flake'`
`error: 'new' is not a recognised command`
 `Did you mean one of key or nar?`

The system is already flake enabled in configuration.nix.

**Comment by TheCodedProf** [comment]
Super sorry about that. I've updated the commands to use the correct feature name (flakes)

**Comment by ztr-pen** [comment]
Thanks @TheCodedProf 

The correct command includes "flakes flake" with correct command being:

`nix --extra-experimental-features nix-command --extra-experimental-features flakes flake new -t github:auxolotl/templates#system NixFiles`

I have created a pull request on the readme.MD for this update.
